spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://postgres:5432/flow-track
    username: ${POSTGRES_USER:-postgres}
    password: ${POSTGRES_PASSWORD:-postgres}

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM:noreply@flowtrack.com}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8888

rabbitmq:
  queue:
    name: messageQueue
  json:
    queue:
      name: jsonMessageQueue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

resilience4j.circuitbreaker:
    instances:
      backendA:
        registerHealthIndicator: true
        slidingWindowSize: 50
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5


