services:
  # ========== Eureka Server ==========
  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://eureka-server:8761/actuator/health || exit 1"]
      interval: 20s
      timeout: 15s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
    - "8087:8087"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_SECRET=${JWT_SECRET:-MATSUMOTO}
    networks:
    - app-network
    restart: unless-stopped

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/flow-track
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
        - JWT_SECRET=${JWT_SECRET:-MATSUMOTO}
        - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
        - SPRING_REDIS_HOST=redis
        - SPRING_REDIS_PORT=6379
    networks:
        - app-network
    restart: unless-stopped

  finance-service:
      build:
        context: .
        dockerfile: finance-service/Dockerfile
      container_name: finance-service
      ports:
        - "8083:8083"
      depends_on:
        eureka-server:
          condition: service_healthy
        postgres:
          condition: service_healthy
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/flow-track
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
        - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      networks:
        - app-network
      restart: unless-stopped

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - CONFIG_GIT_BRANCH=git
      - CONFIG_GIT_URL= #todo
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f  http://localhost:8888/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  postgres:
      image: postgres:15-alpine
      environment:
        POSTGRES_DB: flow-track
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST_AUTH_METHOD: trust
      ports:
        - "5433:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres -d flow-track" ]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 10s
      networks:
        - app-network

  rabbitmq:
      image: rabbitmq:3.13-management
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq
      healthcheck:
        test: [ "CMD-SHELL", "rabbitmq-diagnostics check_port_connectivity" ]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 40s
      restart: unless-stopped
      networks:
        - app-network

  redis:
      image: redis:7-alpine
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
      command: redis-server --appendonly yes
      healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        interval: 5s
        timeout: 3s
        retries: 5
      networks:
        - app-network

volumes:
    postgres-data:
    rabbitmq-data:
    redis-data:

networks:
    app-network:
      driver: bridge