server:
  port: 8087

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: finance-route
          uri: lb://FINANCE-SERVICE
          predicates:
            - Path=/finance/**
          filters:
           - JwtAuthentic
        - id: user-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - JwtAuthentic
        - id: notification-route
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
          filters:
            - JwtAuthentic
     # default-filters: JwtAuthentic


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/