server:
  port: 8087

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: finance-route
          uri: lb://FINANCE-SERVICE
          predicates:
            - Path=/finance/**
          filters:
          ## - JwtAuthenticationFilter
        - id: user-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
          filters:
       ##     - JwtAuthenticationFilter
        - id: notification-route
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
          filters:
     ##       - JwtAuthenticationFilter
     # default-filters: JwtAuthenticationFilter


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/