spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:postgresql://postgres:5432/flow-track
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761