spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:postgresql://postgres:5432/flow-track
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

resilience4j.circuitbreaker:
  instances:
    financeBackend:
      registerHealthIndicator: true
      slidingWindowSize: 50
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10s
      permitted-number-of-calls-in-half-open-state: 5
