spring:
  application:
    name: flowtrack

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/flow-track

    hikari:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: root

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # H2 Console (для разработки)
  #h2:
   # console:
   #   enabled: true

  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Server Configuration

  mail:
    username: rerrr0870@gmail.com
    password: cada gmgs ybua mwou
    properties:
      mail:
        port: 587
        smtp:
          host: smtp.gmail.com
          auth: true
          starttls:
            enable: true

server:
  port: 8080




# Security Configuration

jwt:
  secret: hello
  expiration: PT1H

# RabbitMQ Queues (из вашего producer модуля)
rabbitmq:
  queue:
    name: FirstQueue
  json:
    queue:
      name: jsonQueue
  exchange:
    name: java_exchange
  routing:
    key: java_routing_key
    json:
      key: java_json_routing_key
  queue_with_delay:
    name: hello_world_delay_queue

# User Service Client
user-service:
  base-url: http://localhost:8080

# Logging
logging:
  level:
    root: INFO
    by.kolp.flowtrack: DEBUG