spring.application.name=myappproducer

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queue.name=FirstQueue
rabbitmq.json.queue.name=jsonQueue
rabbitmq.exchange.name=java_exchange
rabbitmq.routing.key=java_routing_key
rabbitmq.routing.json.key=java_json_routing_key
rabbitmq.queue_with_delay.name=hello_world_delay_queue