server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-server:8761/eureka/
    fetch-registry: true
  server:
    peer-node-connect-timeout-ms: 2000
management:
  endpoints:
    web:
      exposure:
        include: health, info # Включаем endpoint 'health'
  endpoint:
    health:
      show-details: always
